# Generated by Django 4.2.1 on 2023-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_technology_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon_link',
            field=models.CharField(max_length=50, verbose_name='Enlace'),
        ),
    ]
